@startuml
@startuml QLcuahang
left to right direction

actor "Actor" as a


rectangle "QL cua hang" {
  usecase "Login" as UC1
  usecase "Quan ly cua hang" as UC2
  usecase "Xem list cac cua hang" as UC3
  usecase "Them cua hang" as UC4
  usecase "Xoa cua hang" as UC5
  usecase "Sua thong tin cua hang" as UC6
  usecase "Trang thai cua hang" as UC7
}

a --> UC2
UC2 ..> UC1: include
UC2 ..> UC3: include

UC2 <.. UC4: extend
UC2 <.. UC5: extend
UC2 <.. UC6: extend

UC7 ..> UC3: extend
@enduml 