@startuml
@startuml QLkhachhang
left to right direction

actor "Actor" as a


rectangle "QL khach hang " {
  usecase "Login" as UC1
  usecase "Quan ly khach hang" as UC2
  usecase "Xem list khach hang" as UC3
  usecase "Them khach hang" as UC4
  usecase "Xoa khach hang" as UC5
  usecase "Sua thong tin khach hang" as UC6
}

a --> UC2
UC2 ..> UC1: include
UC2 ..> UC3: include

UC2 <.. UC4: extend
UC2 <.. UC5: extend
UC2 <.. UC6: extend

@enduml 