@startuml
@startuml Thongke
left to right direction

actor "Actor" as a


rectangle "Thong ke doanh thu" {
  usecase "Login" as UC1
  usecase "Thong ke doanh thu" as UC2
  usecase "Xem bang thong ke tong" as UC3
  usecase "Chon nd muon thong ke" as UC4
  usecase "So sanh thong ke" as UC5
  usecase "Thong ke theo moc thoi gian" as UC6
  usecase "Sap xep cac doi tuong thong ke" as UC7
}

a --> UC2
UC2 ..> UC1: include
UC2 ..> UC3: include

UC2 <.. UC4: extend
UC2 <.. UC5: extend
UC2 <.. UC6: extend

UC7 ..> UC3: extend
@enduml 