@startuml Xem tim kiem san pham


start
:Vao screen Home;
repeat
:Xem san pham;
if (Tim kiem san pham?) then (Yes)
:Vao thanh search;
:Nhap ten/ma sp;
if (Ton tai sp?) then (Co)
:Xem chi tiet san pham;
stop
else (Khong co)
:Thong bao khong ton tai san pham;
endif
else (No)
stop
