@startuml QL cua hang

actor Actor 
boundary StoreManageView 
database Database 

StoreManageView --> Database: 1.Get list of store
StoreManageView --> StoreManageView: 2.Display list of store
Actor --> StoreManageView: 3.Choose action

opt AddNewStore:
Actor --> StoreManageView: Click button add Store
StoreManageView --> Actor: Show form to add Store info
Actor --> StoreManageView: Input store info
StoreManageView --> Database: Save store info
Database --> StoreManageView: Add store successfully
StoreManageView --> Actor: Show list of store
end   

opt DeleteStore:
Actor --> StoreManageView: Click button to delete Store
StoreManageView --> Actor: Show form to confirm delete store
Actor --> StoreManageView: click "yes" to delele store
StoreManageView --> Database: Delete store in database
Database --> StoreManageView: Delete store successfully
StoreManageView --> Actor: Show list of remain store
end

opt EditStoreInfo:
Actor --> StoreManageView: Click button to edit store info
StoreManageView --> Actor: Show form to edit store info
Actor --> StoreManageView: Change store info
StoreManageView --> Database: Edit  store info successfully
Database --> StoreManageView: Edit store successfully
StoreManageView --> Actor: Show form of edited store info
end   


@enduml