@startuml QL khach hang

actor Actor 
boundary CustomerManageView 
database Database 

CustomerManageView  --> Database: 1.Get list of customer
CustomerManageView  --> CustomerManageView : 2.Display list of customer
Actor --> CustomerManageView : 3.Choose action

opt AddNewCustomer:
Actor --> CustomerManageView: Click button add Customer
CustomerManageView --> Actor: Show form to add Customer
Actor --> CustomerManageView: Input customer info
CustomerManageView --> Database: Save customer info
Database --> CustomerManageView: Add customer successfully
CustomerManageView --> Actor: Show list of customer
end   

opt DeleteCustomer:
Actor --> CustomerManageView: Click button to delete Customer
CustomerManageView --> Actor: Show form to check if true
Actor --> CustomerManageView: Click "yes" to confirm
CustomerManageView --> Database: delete customer
Database --> CustomerManageView: Delete customer successfully
CustomerManageView --> Actor: Show list of  remain customer
end


opt EditCustomerInfo:
Actor --> CustomerManageView: Click button to choose customer
CustomerManageView --> Actor: Show form to edit customer info
Actor --> CustomerManageView: Edit info of customer
CustomerManageView --> Database:  change customer info
Database --> CustomerManageView: edit customer info successfully
CustomerManageView --> Actor: Show form of edited customer info
end   


@enduml