@startuml QL nhan vien

actor Actor 
boundary StaffManageView 
database Database 

StaffManageView --> Database: 1.Get list of staff
StaffManageView --> StaffManageView: 2.Display list of staff
Actor --> StaffManageView: 3.Choose action

opt AddNewStaff:
Actor --> StaffManageView: Click button add Nhanvien
StaffManageView --> Actor: Show form to add info
Actor --> StaffManageView: Input nhanvien info
StaffManageView --> Database: Save nhanvien info
Database --> StaffManageView: Add nhanvien successfully
StaffManageView --> Actor: Show list of nhanvien
end   

opt DeleteStaff:
Actor --> StaffManageView: Click button to delete Nhanvien
StaffManageView --> Actor: Show form to check if true
Actor --> StaffManageView: Click "yes" confirm delete nhanvien
StaffManageView --> Database: Delete nhanvien action
Database --> StaffManageView: Delete nhanvien successfully
StaffManageView --> Actor: Show list of remain nhanvien
end

opt EditStaffInfo:
Actor --> StaffManageView: Click button to choose Nhanvien
StaffManageView --> Actor: Show form of nhanvien info
Actor --> StaffManageView: Edit info of nhanvien
StaffManageView --> Database:  edit nhanvien info action
Database --> StaffManageView: edit nhanvien info successfully
StaffManageView --> Actor: Show form of edited info
end

@enduml